### ISSUE TITLE
Comments to project

### ISSUE THREAD

**Issue by Clai101** [Vladimir20Star/2021_super_project_super_group#1]
I have 3 offers/comments: 

- The first one talk that your project involves a huge functions, the best instance is function “game” in the class “Section”. I suggest you divide them on few less functions because Pep-8 don’t approve it.
- The second one, documentation of functions wasn't written. Pep-8 don’t approve it.
- The last one, your project have a lot of similar lines, for example “self.menu_finished = True”. You can use two lists, for, and function zip, to make code clearer.

**Comment by Vladimir20Star** [comment]
Yes, we know about the first and second problems, in the end we will do it. But I want to thank you for letting us know about the latest issue, we will fix it shortly.
